### ISSUE TITLE
Song Name Value "Null" Displays Blank After Saving and Reloading .msup File, But Not Before

### ISSUE THREAD

**Issue by batbrain1998** [MattEqualsCoder/MSUScripter#114]
If you name a song "Null", "NULL" or "null", it will display normally until you save and reload the .msup file. After reloading, the song name will display as blank.

The .msup file does save the "Null" song name, but for some reason the program reads that name, interprets it as a null value and displays nothing in the song name field as a result, but only AFTER loading an .msup file.

This bug only happens if the song is specifically named "Null", "NULL" or "null". Anything else, including "Null " (with a space at the end), "nULL", etc. will display normally.

I haven't tested, but I suspect this bug probably applies to other data fields too.

- [x] Update null strings before writing to yaml and after converting yaml to an object

**Comment by MattEqualsCoder** [comment]
Looks like this is unfortunately an issue with the library I use for saving/loading files. I'll have to come up with some workaround.

**Comment by Vivelin** [comment]
I'd love to know what's going on here. I assume this is the same YAML library we use in SMZ3?

**Comment by MattEqualsCoder** [comment]
You know, that's a good call-out. I don't think my solution would work with SMZ3/the randomizer. 😅 I didn't see any sort of setting for it, so I basically just swap it out with something else and swap it back in projects. But I didn't factor in generating the MSU output YAML. I'll need to dig into this. If Null with a space works, maybe I should just make sure it has a space and trim the output on the randomizer side. Stupid, but it may be the only option. 

I'll do another round of digging into the YAML library. And yeah, it's the same one as SMZ3.

**Comment by Vivelin** [comment]
Oh, I wasn't even thinking about that. Glad I could be some sort of... reverse rubber duck for your debugging, though.

Are you saying the library deserializes `"null"` as `null` rather than "null"? Because while I don't know the YAML spec that well, this feels like a bug.

**Comment by MattEqualsCoder** [comment]
It's been a couple months since I originally looked at this, so I don't remember exactly, but I think it was the opposite. It was serializing a string with the value "`null`" as `null` in the YAML text file. So, when it was deserializing it, it saw just `null` and deserialized it as null accordingly.

I do agree though, this seems like a bug with the library. I should create a small mini console app to verify (just in the off chance I'm doing something I don't realize that's screwing it up), then create a bug for YamlDotNet if I can replicate it there.

**Comment by MattEqualsCoder** [comment]
Okay, after doing some testing, I did confirm that this is default behavior. However, I missed in my research a couple months ago that there's a "WithQuotingNecessaryStrings" option when building the serializer that handles this. Basically it outputs a string with the text "null" as `value: "null"` instead of `value: null`.

Not sure why it's not the default.
